spring.application.name=currency-exchange-service
server.port=8000
spring.config.import=optional:configserver:http://localhost:8888

spring.datasource.url=jdbc:postgresql://localhost:5432/restwebDB
spring.datasource.username =postgres
spring.datasource.password =postgres

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

eureka.instance.hostname=localhost

resilience4j.retry.instances.sample-api.maxAttempts=5
resilience4j.retry.instances.sample-api.wait-duration=2s
resilience4j.retry.instances.sample-api.enable-exponential-backoff=true

#resilience4j.circuitbreaker.instances.default.failure-rate-threshold=90
resilience4j.ratelimiter.instances.deafualt.limit-for-period=2
resilience4j.ratelimiter.instances.deafualt.limit-refresh-period= 10s

resilience4j.bulkhead.instances.deafualt.max-concurrent-calls=10